<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <?php 
    
 
echo $this->tag->linkTo(
    'products',
    'List All Products'
);
;

echo $this->tag->linkTo(
    'products/add',
    'Add New Product'
);



echo $this->tag->linkTo(
    'orders',
    'List All Orders'
);



echo $this->tag->linkTo(
    'orders/add',
    'Add New Order'
);




echo $this->tag->linkTo(
    '/index/Settings',
    'Settings'
);


    ?>
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>